[pytest]
filterwarnings =
    ignore:'oneOf' deprecated - use 'one_of':pyparsing.PyparsingDeprecationWarning
    ignore:'parseString' deprecated - use 'parse_string':pyparsing.PyparsingDeprecationWarning
    ignore:'resetCache' deprecated - use 'reset_cache':pyparsing.PyparsingDeprecationWarning
    ignore:'enablePackrat' deprecated - use 'enable_packrat':pyparsing.PyparsingDeprecationWarning
